name: deploy

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: Byndyusoft/node-reusable-workflows/.github/actions/install@master
        with:
          node-version: "lts/*"

      - run: yarn run build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
